spring.application.name=AppSmartChef

# PostgreSQL Configuration - Render.com
spring.datasource.url=jdbc:postgresql://dpg-d5rmcvur433s738o8tq0-a.virginia-postgres.render.com:5432/smartchef_83hv?sslmode=require
spring.datasource.username=smartchef_83hv_user
spring.datasource.password=rqEtkRDPHjVyXawcBjZFLhIuWEfc8v0A
spring.datasource.driver-class-name=org.postgresql.Driver